server:
  port: 8080

spring:
  datasource:
    username: wt.zhou
    password: cmmdy0328
    url: jdbc:mysql://62.234.41.45:3306/autism?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.zl.autism.model


# PageHelper配置
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
  returnPageInfo: true
  params: count=countSql

#showSql
logging:
  level:
    com:
      example:
        mapper : debugƒ